replicaCount: 3

datastore:
  engine: postgres
  uriSecret: openfga-datastore-credentials
  applyMigrations: true

playground:
  enabled: false

resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: "1"
    memory: 512Mi
