replicaCount: 3

postgresql:
  host: "postgresql"
  port: 5432
  database: "contact_api_prod"
  username: "contact_api_prod"
  existingSecret: "contact-api-db-credentials"

openfga:
  apiUrl: "http://openfga:8080"

resources:
  requests:
    cpu: "250m"
    memory: "256Mi"
  limits:
    cpu: "1"
    memory: "512Mi"
