name: Lint

on:
  pull_request:
    branches: [main]
  push:
    branches: [main, develop]

jobs:
  helmfile-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: helmfile/helmfile-action@v2
        with:
          helmfile-args: lint -e dev
