replicaCount: 1

image:
  repository: "contact-api"
  tag: "latest"
  pullPolicy: "Never"

postgresql:
  host: "postgresql"
  port: 5432
  database: "contact_api_dev"
  username: "contact_api_dev"
  password: "dev-contact-api-password"

openfga:
  apiUrl: "http://openfga:8080"
