replicaCount: 1

postgresql:
  host: "postgresql"
  port: 5432
  database: "contact_api_dev"
  username: "contact_api_dev"
  existingSecret: "contact-api-db-credentials"

openfga:
  apiUrl: "http://openfga:8080"
